export const SQL_KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'INSERT',
  'UPDATE',
  'DELETE',
  'CREATE',
  'DROP',
  'ALTER',
  'TABLE',
  'INDEX',
  'VIEW',
  'DATABASE',
  'SCHEMA',
  'PROCEDURE',
  'FUNCTION',
  'TRIGGER',
  'CONSTRAINT',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'UNIQUE',
  'NOT',
  'NULL',
  'DEFAULT',
  'CHECK',
  'AUTO_INCREMENT',
  'INNER',
  'LEFT',
  'RIGHT',
  'FULL',
  'OUTER',
  'JOIN',
  'ON',
  'UNION',
  'GROUP',
  'BY',
  'HAVING',
  'ORDER',
  'ASC',
  'DESC',
  'LIMIT',
  'OFFSET',
  'DISTINCT',
  'ALL',
  'EXISTS',
  'IN',
  'BETWEEN',
  'LIKE',
  'IS',
  'AND',
  'OR',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'IF',
  'IFNULL',
  'COALESCE',
  'CAST',
  'CONVERT',
  'SUBSTRING',
  'CONCAT',
  'LENGTH',
  'UPPER',
  'LOWER',
  'TRIM',
  'REPLACE',
  'DATE',
  'TIME',
  'DATETIME',
  'TIMESTAMP',
  'YEAR',
  'MONTH',
  'DAY',
  'HOUR',
  'MINUTE',
  'SECOND',
  'NOW',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'FIRST',
  'LAST',
  'TOP',
  'AS',
  'ALIAS',
];

export interface SQLFunctionSnippet {
  name: string;
  insertText: string;
  detailKey: string;
  documentationKey: string;
}

export const SQL_FUNCTIONS: SQLFunctionSnippet[] = [
  {
    name: 'COUNT',
    insertText: 'COUNT(${1:*})',
    detailKey: 'codeEditor.detail.aggregateFunction',
    documentationKey: 'codeEditor.docs.countRows',
  },
  {
    name: 'SUM',
    insertText: 'SUM(${1:column})',
    detailKey: 'codeEditor.detail.aggregateFunction',
    documentationKey: 'codeEditor.docs.sumColumn',
  },
  {
    name: 'AVG',
    insertText: 'AVG(${1:column})',
    detailKey: 'codeEditor.detail.aggregateFunction',
    documentationKey: 'codeEditor.docs.avgColumn',
  },
  {
    name: 'MAX',
    insertText: 'MAX(${1:column})',
    detailKey: 'codeEditor.detail.aggregateFunction',
    documentationKey: 'codeEditor.docs.maxColumn',
  },
  {
    name: 'MIN',
    insertText: 'MIN(${1:column})',
    detailKey: 'codeEditor.detail.aggregateFunction',
    documentationKey: 'codeEditor.docs.minColumn',
  },
  {
    name: 'CONCAT',
    insertText: 'CONCAT(${1:str1}, ${2:str2})',
    detailKey: 'codeEditor.detail.stringFunction',
    documentationKey: 'codeEditor.docs.concatStrings',
  },
  {
    name: 'SUBSTRING',
    insertText: 'SUBSTRING(${1:string}, ${2:start}, ${3:length})',
    detailKey: 'codeEditor.detail.stringFunction',
    documentationKey: 'codeEditor.docs.substring',
  },
  {
    name: 'UPPER',
    insertText: 'UPPER(${1:string})',
    detailKey: 'codeEditor.detail.stringFunction',
    documentationKey: 'codeEditor.docs.upper',
  },
  {
    name: 'LOWER',
    insertText: 'LOWER(${1:string})',
    detailKey: 'codeEditor.detail.stringFunction',
    documentationKey: 'codeEditor.docs.lower',
  },
  {
    name: 'NOW',
    insertText: 'NOW()',
    detailKey: 'codeEditor.detail.dateFunction',
    documentationKey: 'codeEditor.docs.now',
  },
];
